### ISSUE TITLE
[ERROR] Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [synclounge/synclounge#191] opened 2020-04-25 21:50 UTC
### Web App
You can remove this section if your issue isn't related to the Web App

**System Details**

- Operating System: Windows
- Web Browser name and version: Chrome & Firefox, both an latest versions

**Plex Media Server details**

- Version: 1.19.2.2702
- Operating System (Windows/Linux/Mac): Linux
- Running in Docker? (Yes/No): No
- Location (Local/Remote): Remote
- Remote Access Enabled (Yes/No)?: Yes

**Plex Client details**

- Name: Synclounge Web
- Version: Synclounge Web  latest version
- Network connection (Wired/Wifi): Wifi
- Platform: Synclounge Web

### Self-Hosting
You can remove this section if your issue isn't related to Self-Hosting

**System Details**

- Operating System: Linux

**SyncLounge Details**

- Running in Docker? (Yes/No): No
- Using a Reverse Proxy (Yes/No): Yes
    If Yes, which Reverse Proxy (Nginx, Apache, Caddy, etc.): Nginx

### Issue information

**To Reproduce**

1) Set up a room.
2) Play a video file from a library.
3) Wait and see error message appear on screen.

**Describe your bug/issue**
Chrome keeps showing this error ```Failed to execute 'appendBuffer' on 'SourceBuffer': The SourceBuffer is full, and cannot free space to append additional buffers.``` on some items being played like a minute in to the video.

Firefox also keeps showing ```The quota has been exceeded.```

Everything works well when watching things through Plex Web, so it's not connection.

**Comment by remyjette** [comment] 2020-05-02 17:23
Hitting this too. Setting a transcode option to a lower bitrate was a workaround for me.

**Comment by gcordalis** [comment] 2020-05-05 08:48
It’s a known issue with the video player we use. We’re working on a fix but no eta

**Comment by ttshivers** [comment] 2020-05-18 21:28
The issue is not fixed with latest videojs versions, but the developers are aware of it and may fix it in later releases.
![image](https://user-images.githubusercontent.com/728370/82261447-9bcd0b00-9924-11ea-81e2-c20260716357.png)

**Comment by ctindel** [comment] 2020-07-01 17:58
I hit this problem quite often as well, and always on media where the plex web player has no problem with it.  Is there a reason that synclounge can't use the same browser video player that plex does?

**Comment by ttshivers** [comment] 2020-07-01 22:36
We have been working on vastly improving the synclounge web player and in a future release, it should be on par with the Plex web player.

**Comment by ctindel** [comment] 2020-07-04 07:14
Yeah I guess I just don't understand why "the synclounge player" isn't the exact same component as the plex web player so that anything that plays in plex is guaranteed to play properly in synclounge. 

Is the plex player really proprietary in a way that isn't reusable?

**Comment by remyjette** [comment] 2020-07-04 07:17
Plex isn't open source. The Plex player is not distributed under an open source license.

**Comment by ctindel** [comment] 2020-07-04 12:48
I understand, I just assumed that something as basic as playing a video stream was technology that has been worked out for a long time and was an open source component that everybody used because Netflix, prime video, YouTube, Plex, Facebook, etc are all pretty stable. 

Is it really the case that all of those sites use custom closed source components to play streaming video in a browser?

**Comment by ttshivers** [comment] 2020-07-23 04:06
This issue is fixed in #220

**Closed** 2020-09-29 00:02 UTC
Labels: no-issue-activity
